swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0

host: localhost
schemes:
  - http

paths:

  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - service/json
      responses:
        200:
          description: OK
  /employees:
    get:
      summary: ndeu
      description: deiddni

      responses:
        200:
          description: OK
      produces:
        - Employee
